export const SERVICE_DETAILS = {
  "Mutual Funds & SIP": `
Mutual funds allow investors to invest in a professionally managed portfolio of securities through a single investment. A Systematic Investment Plan (SIP) lets you invest a fixed amount at regular intervals, while a lumpsum investment allows you to invest a larger amount at once. We help you understand different fund categories, investment objectives, expense ratios, time horizons and associated risks before selecting suitable options. Whether you are starting your investment journey or reviewing an existing portfolio, our guidance focuses on aligning investments with your financial goals and risk comfort. We also encourage periodic reviews so your investment strategy can adapt when your goals or circumstances change. Mutual fund investments are subject to market risks, and returns are not guaranteed.
`,

  "Goal-Based Investment": `
Every financial goal needs a clear plan, an estimated cost and a realistic timeline. Goal-based investment helps you prepare for important milestones such as higher education, buying a home, marriage, retirement or building an emergency fund. We help you estimate the amount you may need, understand your investment horizon and explore options that match your risk tolerance. The approach also considers how much you can invest regularly and whether your existing savings contribute towards the goal. Periodic reviews can help you track progress and make adjustments when your income, priorities or timelines change. A well-structured plan can bring clarity and discipline to financial decisions, although investment outcomes depend on market conditions and are never guaranteed.
`,

  "Portfolio Review": `
A portfolio review helps you understand whether your existing investments continue to support your financial goals. We review the broad allocation of your investments, exposure to different asset classes, fund overlap, investment costs, risk concentration and suitability for your time horizon. The review can highlight areas that may need attention, such as excessive concentration in similar investments or a mismatch between risk and financial needs. Based on the information available, we explain observations and possible adjustments in straightforward language so you can make informed decisions. A review is also useful after major life changes or when your goals evolve. Recommendations depend on your individual circumstances, and past performance does not guarantee future returns.
`,

  NFO: `
A New Fund Offer (NFO) is the initial offering through which an asset management company introduces a new mutual fund scheme. An NFO may sound attractive, but a new scheme does not automatically provide better value or higher returns. We help you understand the fund's investment objective, proposed strategy, benchmark, asset allocation, costs, risks and how it differs from existing schemes. We also discuss whether the fund category is relevant to your goals and investment horizon. Instead of deciding only because a scheme is new or has a particular launch price, investors should evaluate its purpose and suitability within their overall portfolio. All investments involve risk, and an NFO's future performance cannot be predicted or guaranteed.
`,

  "Bonds & NCDs": `
Bonds and Non-Convertible Debentures (NCDs) are debt instruments through which investors lend money to an issuer under specified terms. Depending on the instrument, investors may receive interest payments and repayment of principal at maturity. We help you compare available options by reviewing the issuer, credit rating, interest structure, tenure, liquidity, redemption conditions and potential yield. Understanding these factors is important because a higher advertised return may also involve higher risk. We explain the main terms in simple language so you can assess whether a fixed-income investment fits your income needs and financial timeline. Bonds and NCDs are not risk-free; credit, interest-rate and liquidity risks may affect the investment and repayment.
`,

  "Fixed Deposits": `
Fixed deposits allow you to place a specified amount with a bank or other eligible institution for a chosen tenure, usually at an agreed interest rate. They may be useful for people who prefer predictable interest terms and want to plan around a known financial timeline. We help you compare available deposit options by reviewing the institution, applicable interest rate, tenure, payout frequency, premature-withdrawal conditions and relevant deposit-protection rules. We also help you consider when the funds may be needed so that the chosen maturity date is practical for your circumstances. Before investing, it is important to understand the institution's terms and the risks involved. Rates, eligibility and protection limits vary, and corporate deposits may carry additional credit risk.
`,

  IPO: `
An Initial Public Offering (IPO) gives a company an opportunity to offer shares to public investors. Before applying, investors should understand the company's business, financial information, issue price band, issue size, offer dates and intended use of proceeds. We help you navigate the IPO application process through the available authorised platform and explain important information investors should review before making a decision. An application does not guarantee share allotment, and listing gains are never assured. The market price after listing may rise or fall, including below the issue price. Investors should evaluate the company's disclosures, financial position and risks rather than applying solely because an IPO is popular. Investment decisions should reflect your financial circumstances and risk tolerance.
`,

  "Demat & Share Trading": `
A demat account holds securities electronically, while a trading account allows you to place eligible buy and sell orders through a broker. We guide you through the account-opening process, explain the documents and verification steps generally required, and help you understand the trading platform and its key features. We also discuss common charges, order types, settlement basics and the importance of keeping account credentials secure. Before trading, it is useful to establish clear financial limits and understand the difference between investing and short-term trading. Shares can fluctuate significantly in value, and frequent trading can increase costs and losses. Our goal is to help you understand the process and risks so you can make informed decisions independently.
`,

  "Equity/Commodity Research": `
Equity and commodity research examines information that may help investors understand markets, businesses and price movements. Equity research can consider company fundamentals, financial results, valuation, industry conditions and relevant developments. Commodity research may examine supply and demand, global events, inventories and other market factors. We aim to present research observations and market information in clear language, helping clients understand the reasoning, assumptions and risks behind a view. Research should be considered alongside an individual's goals, financial position and tolerance for loss rather than followed blindly. Market conditions can change quickly, and research opinions may not turn out as expected. No research view can guarantee profits, and commodity trading may involve substantial risk, particularly when leverage is used.
`,

  PMS: `
Portfolio Management Services (PMS) provide eligible investors with a professionally managed portfolio under a defined investment mandate. Strategies, securities, minimum investment requirements, fees and levels of risk can differ between providers and offerings. We help you understand the proposed strategy, investment approach, portfolio concentration, performance presentation, charges, liquidity terms and the risks disclosed in the relevant documents. It is important to compare a PMS with other investment approaches and evaluate whether its structure fits your financial objectives and ability to bear losses. Past performance alone is not a reliable indicator of future outcomes. Before proceeding, investors should review the provider's documentation, eligibility conditions and fee structure carefully. PMS investments can involve market and concentration risks, and returns are not guaranteed.
`,

  "AIF / SIF / IAP": `
Alternative Investment Funds (AIFs), Specialised Investment Funds (SIFs) and Investment Advisory services have different structures, eligibility requirements and regulatory conditions. Depending on the offering, these options may use specialised strategies or provide a different approach to portfolio construction compared with conventional investments. We help you understand the product structure, minimum investment amount, fees, lock-in or liquidity conditions, investment strategy and potential risks described in the official documents. Suitability should be assessed carefully because these products may not be appropriate for every investor and some strategies can be complex. We encourage clients to understand the downside scenarios and the provider's terms before committing funds. Eligibility, availability and regulatory requirements vary by product, and no investment return can be guaranteed.
`,

  "Life & Term Insurance": `
Life insurance can help provide financial support to your chosen beneficiaries if an insured event covered by the policy occurs. Term insurance generally offers life cover for a specified period, subject to the policy terms and conditions. We help you estimate an appropriate level of protection by considering income, dependants, outstanding loans, future family expenses and existing coverage. We also explain key policy details such as premium payments, policy duration, exclusions, claim requirements and available options. Choosing cover involves balancing affordability with the financial needs of your family. It is important to provide accurate information in the application and read the policy wording carefully. Coverage, eligibility and claim decisions depend on the insurer's terms; no policy should be selected without understanding its conditions.
`,

  "Health Insurance": `
Health insurance can help cover eligible medical expenses according to the policy's benefits, limits and exclusions. We help you compare available plans by looking at sum insured, hospitalisation coverage, waiting periods, room limits, co-payments, network hospitals, pre-existing-condition rules and the claim process. Understanding these terms before purchasing can help reduce confusion when medical treatment is needed. We also explain the importance of accurate disclosures and reviewing whether the policy suits your household's requirements and budget. Coverage differs across insurers and policies, so a lower premium should not be the only selection criterion. Claims remain subject to policy terms, eligibility and documentation. Reviewing coverage periodically can help you assess whether it continues to meet your needs as circumstances change.
`,

  "Vehicle Insurance": `
Vehicle insurance helps protect vehicle owners against specified financial liabilities and losses, depending on the policy selected. Third-party insurance covers eligible third-party liabilities, while a comprehensive policy may also cover certain damage to your own vehicle, subject to terms and exclusions. We help you understand policy types, insured declared value where applicable, deductibles, add-on covers, premium factors and renewal dates. We also explain the basic documentation that may be needed when reporting a claim and why accurate information is important. Before renewing, it is sensible to compare coverage and conditions rather than choosing only by price. Claim approval depends on the policy wording, circumstances and required documentation. We aim to make the purchase and renewal process clearer and easier to navigate.
`,

  "ITR, TDS & Tax Planning": `
Tax filing and planning involve organising financial information, understanding applicable tax rules and meeting relevant deadlines. We assist with income-tax return preparation using the documents and information provided, and help explain common items such as salary income, interest income, eligible deductions, tax payments and Tax Deducted at Source (TDS). Where relevant, we can help review available tax-planning options under applicable law and explain what records may be required. Accurate disclosure is important because incorrect or incomplete information can cause delays, notices or additional liabilities. Tax treatment depends on the individual's circumstances and the rules applicable for the relevant financial year. Our approach focuses on timely, lawful compliance and clear communication; it does not involve hiding income or claiming ineligible benefits.
`,

  "NRI / GIFT City": `
NRI investment requirements and opportunities associated with GIFT City can involve specific eligibility, account, documentation, tax and regulatory considerations. The available investment routes may depend on residency status, the product, the relevant financial institution and applicable Indian and overseas regulations. This service is currently coming soon, so detailed onboarding and product availability are not yet being offered through this page. When the service becomes available, the aim will be to help interested individuals understand the general process, documentation requirements, product features and important risks before proceeding. Investors should verify eligibility and obtain appropriate tax or legal guidance where necessary. Availability, rules and product terms may change, and no investment outcome or return can be promised in advance.
`,
};